          $Password = "RdpSuperStrong2026!@#"
          $SecurePass = ConvertTo-SecureString $Password -AsPlainText -Force
          New-LocalUser -Name "RDP" -Password $SecurePass -AccountNeverExpires
          Add-LocalGroupMember -Group "Administrators" -Member "RDP"
          
          Write-Host "======================================"
          Write-Host "KULLANICI : RDP"
          Write-Host "ŞİFRE     : RdpSuperStrong2026!@#"
          Write-Host "======================================"
